# Generated by Django 5.2.1 on 2025-05-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_lesson_owner_alter_quiz_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
